// <auto-generated />
using System;
using ConsoleApp14entity2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp14entity2.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp14entity2.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Toyota",
                            Model = "Toyota Camry",
                            Price = 25000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            Make = "Honda",
                            Model = "Honda Civic",
                            Price = 22000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            Make = "BMW",
                            Model = "BMW 3 Series",
                            Price = 35000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            Make = "Audi",
                            Model = "Audi A4",
                            Price = 38000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 5,
                            Make = "Mercedes-Benz",
                            Model = "Mercedes-Benz C-Class",
                            Price = 45000m,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("ConsoleApp14entity2.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "johndoe@example.com",
                            Name = "John Doe"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "janesmith@example.com",
                            Name = "Jane Smith"
                        },
                        new
                        {
                            CustomerId = 3,
                            Email = "bobbrown@example.com",
                            Name = "Bob Brown"
                        },
                        new
                        {
                            CustomerId = 4,
                            Email = "alicej@example.com",
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            CustomerId = 5,
                            Email = "charliew@example.com",
                            Name = "Charlie White"
                        },
                        new
                        {
                            CustomerId = 6,
                            Email = "davidg@example.com",
                            Name = "David Green"
                        },
                        new
                        {
                            CustomerId = 7,
                            Email = "emmab@example.com",
                            Name = "Emma Blue"
                        },
                        new
                        {
                            CustomerId = 8,
                            Email = "frankb@example.com",
                            Name = "Frank Black"
                        },
                        new
                        {
                            CustomerId = 9,
                            Email = "gracey@example.com",
                            Name = "Grace Yellow"
                        },
                        new
                        {
                            CustomerId = 10,
                            Email = "henryr@example.com",
                            Name = "Henry Red"
                        });
                });

            modelBuilder.Entity("ConsoleApp14entity2.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Name = "John Smith"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Name = "Jane Doe"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Name = "Mark Johnson"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Name = "Emily White"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Name = "Michael Brown"
                        });
                });

            modelBuilder.Entity("ConsoleApp14entity2.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            CarId = 1,
                            CustomerId = 1,
                            Date = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1
                        },
                        new
                        {
                            SaleId = 2,
                            CarId = 2,
                            CustomerId = 2,
                            Date = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2
                        },
                        new
                        {
                            SaleId = 3,
                            CarId = 3,
                            CustomerId = 3,
                            Date = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3
                        },
                        new
                        {
                            SaleId = 4,
                            CarId = 4,
                            CustomerId = 4,
                            Date = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4
                        },
                        new
                        {
                            SaleId = 5,
                            CarId = 5,
                            CustomerId = 5,
                            Date = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5
                        });
                });

            modelBuilder.Entity("ConsoleApp14entity2.ServiceHistory", b =>
                {
                    b.Property<int>("ServiceHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceHistoryId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ServiceHistoryId");

                    b.HasIndex("CarId");

                    b.ToTable("ServiceHistories");
                });

            modelBuilder.Entity("ConsoleApp14entity2.Sale", b =>
                {
                    b.HasOne("ConsoleApp14entity2.Car", "Car")
                        .WithMany("Sales")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp14entity2.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp14entity2.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ConsoleApp14entity2.ServiceHistory", b =>
                {
                    b.HasOne("ConsoleApp14entity2.Car", "Car")
                        .WithMany("ServiceHistories")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ConsoleApp14entity2.Car", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("ServiceHistories");
                });

            modelBuilder.Entity("ConsoleApp14entity2.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ConsoleApp14entity2.Employee", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
